---
title: "R Notebook"
output: html_notebook
---


```{r}
rm(list=ls())

library(cluster)
library(reshape)
library(ggplot2)
library(pROC)
library(caret)
library(glmnet)

patient_summary<-read.csv('/zfsauton/project/public/Jessie/EEG/middle/PatientSummary.csv')

source("/home/mdeartea/repos/caa/Method/CAA_utils.R")
source("/home/mdeartea/repos/caa/Method/CAA_classify.R")
source("/home/mdeartea/repos/caa/Source/ggplot2ROC.R")
setwd("/home/mdeartea/Documents/CAA/EEG/")

load('charWithEEG_p3_02sparse_disjointsetslast36h.RData')
```


```{r}
patients<-unique(proj_data[,1])
patient_summary<-patient_summary[which(patient_summary$SubjectID%in%patients),]
set.seed(42)
Folds<-createFolds(patient_summary$Good_Outcome,k=10)
```



```{r}
#last column should be response vector as "Yes" and "No"
Logit_cv<-function(M, Folds, patient_summary, patients){
M_true_pred<-matrix(NA,ncol=3,nrow=0)
for(fold in Folds){
  #find set of patients in training and testing 
  fold = unlist(fold)
  patients_fold<-as.vector(patient_summary[fold,'SubjectID'])
  idx_train<-!(patients%in%patients_fold)
  idx_test<-patients%in%patients_fold
  M_train<-M[idx_train,-ncol(M)]
  M_test<-M[idx_test,-ncol(M)]
  response_train<-factor(M[idx_train,ncol(M)],levels=c('No','Yes'))
  response_test<-factor(M[idx_test,ncol(M)],levels=c('No','Yes'))
  patients_test<-patients[idx_test]
  M_train<-apply(M_train,2,as.numeric)
  M_test<-apply(M_test,2,as.numeric)
  logit<-cv.glmnet(M_train,response_train,family=c('binomial'),alpha=1)
  logit_pred<-predict.cv.glmnet(logit,M_test)
  M_true_pred<-rbind(M_true_pred,cbind(logit_pred,response_test,patients_test))
}
M_true_pred[,1]<-as.numeric(as.character(M_true_pred[,1]))
M_true_pred[,2]<-as.numeric(as.character(M_true_pred[,2]))
return(M_true_pred)
}

```

Pointwise classification - take last data point for each patient (hour 36) and train/test with that

Create data for pointwise analysis
```{r}

df_pointwise<-matrix(NA,ncol=(nrow(All_U)+1),nrow=length(EEG))

for(i in 1:length(EEG)){
  EEG_i<-as.matrix(EEG[[i]])
  p<-patients[i]
  var_i<-c(EEG_i[nrow(EEG_i),],proj_data[which(proj_data[,1]==p),2][1])
  df_pointwise[i,]<-var_i
}
```


Aggregate over the two hours, for each feature calculate (min,max,mean,q25,q75)

```{r}
df_sets<-matrix(NA,ncol=(5*nrow(All_U)+1),nrow=length(EEG))
for(i in 1:length(EEG)){
  p<-patients[i]
  label<-proj_data[which(proj_data[,1]==p),2][1]
  EEG_i<-as.matrix(EEG[[i]])
  df_sets[i,]<-c(as.vector(apply(EEG_i,2,quantile)),label)
}
```


Train/evaluate both models with 10-fold cross-validation
```{r}
M_true_pred_points<-Logit_cv(df_pointwise, Folds, patient_summary, patients)
M_true_pred_sets<-Logit_cv(df_sets, Folds, patient_summary, patients)

M_true_pred_sets[M_true_pred_sets[,2]==2,2]<-'Yes'
M_true_pred_sets[M_true_pred_sets[,2]==1,2]<-'No'
```


```{r}
source("/home/mdeartea/repos/caa/Source/ROC_log.R")
roc_logit<-ROCplot(M_true_pred_sets[,2],as.numeric(M_true_pred_sets[,1]),'images/roc/Logit/Logit_sets_neg.jpg',targ_class='negative',color='red',log=F)
```



```{r}
roc_knn <- roc(M_true_pred_sets[,2],as.numeric(M_true_pred_sets[,1]))
```


```{r}
roc_points<-ROCplot(M_true_pred_points[,2],as.numeric(M_true_pred_points[,1]),'images/roc/logit_points.jpg',targ_class='positive',log=FALSE)
```



```{r}
save(M_true_pred_sets,M_true_pred_points,file='Results/results_logit.Rdata')
```




```{r}
roc_sets<-ROCplot(M_true_pred_sets[,2],as.numeric(M_true_pred_sets[,1]),'images/roc/logit_set.jpg',targ_class='positive',log=FALSE)
roc_sets<-ROCplot(M_true_pred_sets[,2],as.numeric(M_true_pred_sets[,1]),'images/roc/logit_set_log.jpg',targ_class='positive',log=TRUE)
```
